#Server port
server:
  port: 8080
  address: localhost

spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # cloud DB
    # url: jdbc:mysql://
    # local DB
    url: jdbc:mysql://localhost:3306/interview?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    # formatter
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    # using database
    database: mysql
    # mysql ?? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Redis
  data:
    redis:
      port: 6379
      host: 127.0.0.1 # Redis ??? ??? ?? ??
      pool:
        min-idle: 0 # ???? ?? ?? ?? ???
        max-idle: 8
        max-active: 8 # ??? ??? ? ?? ?? ?? ?
